# Generated by Django 3.1.7 on 2021-03-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostMonster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsterName', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='bd/img/')),
            ],
        ),
        migrations.CreateModel(
            name='PostSurvivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survivorName', models.CharField(max_length=255)),
                ('age', models.TimeField()),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='bd/img/')),
            ],
        ),
    ]
