# Generated by Django 3.1.7 on 2021-03-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmonster',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='postsurvivor',
            name='age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postsurvivor',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
