# Generated by Django 3.1.7 on 2021-03-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210316_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmonster',
            old_name='monsterName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='postsurvivor',
            old_name='survivorName',
            new_name='Name',
        ),
    ]
