# Generated by Django 3.1.7 on 2021-03-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210316_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmonster',
            name='tipo',
            field=models.CharField(choices=[('S', 'Superviviente'), ('M', 'Monstruo')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='postsurvivor',
            name='tipo',
            field=models.CharField(choices=[('S', 'Superviviente'), ('M', 'Monstruo')], default='', max_length=1),
        ),
    ]
